version: '3'
services:
  nginx:
    build: ./docker/nginx
    container_name: my-apotheke-nginx
    links:
      - php
    network_mode: bridge
    ports:
      - "${APP_HTTP_PORT}:${APP_HTTP_PORT}"
    volumes:
      - ./docker/nginx/hosts:/etc/nginx/conf.d
      - ./var/log/nginx:/var/log/nginx
      - ./:${APP_DIR}
    restart: always
  php:
    build: ./docker/php
    container_name: my-apotheke-php
    network_mode: bridge
    volumes:
      - ./:${APP_DIR}
    restart: always